const FluxActionTypes ={
    //Categories action types
CATEGORIES_LOADING:'CATEGORIES_LOADING',
CATEGORIES_FAILED:'CATEGORIES_FAILED',
GIT_CATEGORIES:'GIT_CATEGORIES',

  //Cart action types
CART_LOADING:'CART_LOADING',
CART_FAILED:'CART_FAILED',
RETRIVE_CART:'RETRIVE_CART',
REFRESH_CART:'REFRESH_CART',
ADD_TO_CART:'ADD_TO_CART',
MINUS_FROM_CART:'MINUS_FROM_CART',
REMOVE_FROM_CART:'REMOVE_FROM_CART',
EMPTY_CART:'EMPTY_CART',
GENERATE_TOKEN:'GENERATE_TOKEN',



}

export default FluxActionTypes;